"""Purple Trade API."""
from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ValidationError

from . import ai
from .csvdata import CsvError, parse_csv
from .describe import describe, validate
from .engine import bars_hash, run_backtest, strategy_hash
from .sample import TEMPLATES, synthetic_bars
from .schema import Strategy
from .store import Store, default_store


class NewStrategy(BaseModel):
    name: str = "Untitled strategy"
    template_id: str | None = None

class ChatIn(BaseModel):
    message: str

class BacktestIn(BaseModel):
    strategy_id: str
    dataset_id: str
    version_id: str | None = None  # None = current draft (unapproved)


def create_app(store: Store | None = None, provider=None) -> FastAPI:
    app = FastAPI(title="Purple Trade", version="0.1.0")
    db = store or default_store()
    app.state.store = db
    app.state.provider = provider or ai.default_provider()

    if not any(d["synthetic"] for d in db.list_datasets()):
        bars = synthetic_bars()
        db.add_dataset("SAMPLE — synthetic prices (not market data)", "SAMPLE",
                       "Generated by Purple Trade for trying the app. Not real NSE prices.",
                       bars, bars_hash(bars), synthetic=True)

    def _strategy_or_404(sid: str) -> dict:
        s = db.get_strategy(sid)
        if not s:
            raise HTTPException(404, "Strategy not found")
        return s

    def _review(body: dict) -> dict:
        try:
            st = Strategy.model_validate(body)
        except ValidationError as e:
            return {"valid_shape": False, "shape_errors": [
                f"{'.'.join(str(p) for p in err['loc'])}: {err['msg']}" for err in e.errors()[:8]]}
        return {"valid_shape": True, "strategy": st.model_dump(), "describe": describe(st),
                "validation": validate(st), "hash": strategy_hash(st)}

    # ----- meta -----
    @app.get("/api/health")
    def health():
        return {"ok": True, "ai": app.state.provider.status()}

    @app.get("/api/templates")
    def templates():
        return [{**t, "review": _review(t["strategy"])} for t in TEMPLATES]

    # ----- strategies -----

    @app.get("/api/strategies")
    def list_strategies():
        return db.list_strategies()

    @app.post("/api/strategies")
    def create_strategy(body: NewStrategy):
        s = db.create_strategy(body.name.strip() or "Untitled strategy")
        if body.template_id:
            t = next((t for t in TEMPLATES if t["id"] == body.template_id), None)
            if not t:
                raise HTTPException(400, "Unknown template")
            st = Strategy.model_validate(t["strategy"])
            db.save_draft(s["id"], st.model_dump(), name=st.name)
        return get_strategy(s["id"])

    @app.get("/api/strategies/{sid}")
    def get_strategy(sid: str):
        s = _strategy_or_404(sid)
        return {**s, "review": _review(s["draft"]) if s["draft"] else None}

    @app.delete("/api/strategies/{sid}")
    def delete_strategy(sid: str):
        _strategy_or_404(sid)
        db.delete_strategy(sid)
        return {"ok": True}

    @app.post("/api/review")
    def review(body: dict):
        """Validate and describe a strategy without saving (used live while editing)."""
        return _review(body)

    @app.put("/api/strategies/{sid}/draft")
    def save_draft(sid: str, body: dict):
        _strategy_or_404(sid)
        r = _review(body)
        if not r["valid_shape"]:
            raise HTTPException(422, {"shape_errors": r["shape_errors"]})
        db.save_draft(sid, r["strategy"], name=r["strategy"]["name"])
        return get_strategy(sid)


    @app.post("/api/strategies/{sid}/ai")
    def ai_propose(sid: str, body: ChatIn):
        s = _strategy_or_404(sid)
        msg = body.message.strip()
        if not msg:
            raise HTTPException(400, "Empty message")
        current = Strategy.model_validate(s["draft"]) if s["draft"] else None
        try:
            result = ai.propose(msg, current, s["chat"], app.state.provider)
        except ai.ProviderError as e:
            raise HTTPException(503, str(e)) from e
        reply = result["notes"] or ("" if result["ok"] else result["error"])
        if result["questions"]:
            reply = (reply + "\n" if reply else "") + "\n".join(f"• {q}" for q in result["questions"])
        db.append_chat(sid, {"role": "user", "content": msg},
                       {"role": "assistant", "content": reply or "Proposal ready.", "proposal": result["ok"] and result["strategy"] is not None})
        if result["strategy"]:
            result["review"] = _review(result["strategy"])
        return result

    @app.post("/api/strategies/{sid}/approve")
    def approve(sid: str):
        s = _strategy_or_404(sid)
        if not s["draft"]:
            raise HTTPException(400, "Nothing to approve yet")
        st = Strategy.model_validate(s["draft"])
        v = validate(st)
        if not v["ok"]:
            raise HTTPException(409, {"errors": v["errors"]})
        h = strategy_hash(st)
        if s["versions"] and db.get_version(s["versions"][0]["id"])["hash"] == h:
            raise HTTPException(409, {"errors": [f"Identical to version {s['versions'][0]['number']} — nothing changed."]})
        db.add_version(sid, st.model_dump(), h)
        return get_strategy(sid)

    @app.get("/api/versions/{vid}")
    def get_version(vid: str):
        v = db.get_version(vid)
        if not v:
            raise HTTPException(404, "Version not found")
        return {**v, "review": _review(v["body"])}

    # ----- datasets -----
    @app.get("/api/datasets")
    def list_datasets():
        return db.list_datasets()

    @app.post("/api/datasets")
    async def upload_dataset(file: UploadFile = File(...), symbol: str = Form(""), source_note: str = Form("")):
        data = await file.read()
        try:
            bars, warnings = parse_csv(data)
        except CsvError as e:
            raise HTTPException(422, str(e)) from e
        h = bars_hash(bars)
        existing = db.find_dataset_by_hash(h)
        if existing:
            return {**existing, "warnings": warnings + ["Identical data was already imported — reusing it."]}
        sym = symbol.strip().upper() or None
        name = f"{sym or Path(file.filename or 'upload').stem} · {bars[0].date} → {bars[-1].date}"
        meta = db.add_dataset(name, sym, source_note.strip() or None, bars, h)
        return {**meta, "warnings": warnings}

    @app.get("/api/datasets/{did}/bars")
    def dataset_bars(did: str):
        bars = db.get_bars(did)
        if bars is None:
            raise HTTPException(404, "Dataset not found")
        return [b.__dict__ for b in bars]

    # ----- backtests -----

    @app.post("/api/backtests")
    def backtest(body: BacktestIn):
        s = _strategy_or_404(body.strategy_id)
        if body.version_id:
            v = db.get_version(body.version_id)
            if not v or v["strategy_id"] != s["id"]:
                raise HTTPException(404, "Version not found")
            st_body = v["body"]
        else:
            if not s["draft"]:
                raise HTTPException(400, "No strategy to test yet")
            st_body = s["draft"]
        st = Strategy.model_validate(st_body)
        v = validate(st)
        hard = [e for e in v["errors"] if "open question" not in e]
        if hard:
            raise HTTPException(409, {"errors": hard})
        bars = db.get_bars(body.dataset_id)
        if bars is None:
            raise HTTPException(404, "Dataset not found")
        if len(bars) <= v["warmup_bars"] + 1:
            raise HTTPException(409, {"errors": [f"Dataset has {len(bars)} rows but the rules need "
                                                 f"{v['warmup_bars']} bars of warm-up plus at least one more."]})
        result = run_backtest(st, bars)
        result["dataset"] = db.get_dataset_meta(body.dataset_id)
        result["describe"] = describe(st)
        result["mode"] = "approved" if body.version_id else "draft"
        rid = db.add_run(s["id"], body.version_id, body.dataset_id, st.model_dump(), result)
        return {"id": rid, **result}

    @app.get("/api/strategies/{sid}/runs")
    def list_runs(sid: str):
        _strategy_or_404(sid)
        return db.list_runs(sid)

    @app.get("/api/runs/{rid}")
    def get_run(rid: str):
        r = db.get_run(rid)
        if not r:
            raise HTTPException(404, "Run not found")
        return {"id": r["id"], **r["result"]}

    # ----- frontend (production build) -----
    dist = Path(__file__).resolve().parents[2] / "frontend" / "dist"
    if dist.is_dir():
        app.mount("/assets", StaticFiles(directory=dist / "assets"), name="assets")

        @app.get("/{path:path}", include_in_schema=False)
        def spa(path: str):
            f = dist / path
            if path and f.is_file() and dist in f.resolve().parents:
                return FileResponse(f)
            return FileResponse(dist / "index.html")

    return app
